name: IFJ Project CHECK

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Compile (according to Makefile)
      run: make

  makeRunAndDebug:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Compile (according to Makefile)
      run: make
    - name: Try running compiled program
      continue-on-error: true
      run: ./compilerIFJ2020 < tests/main.go
    - name: Compile with debug (according to Makefile)
      run: make debug
    - name: Run debug - Empty function (main)
      continue-on-error: true
      run: ./compilerIFJ2020 < tests/emptyFunc.go
    - name: Run debug - Function newFnc with arguments, return type and function call inside
      continue-on-error: true
      run: ./compilerIFJ2020 < tests/fncCallFuncArgRet.go
    - name: Run debug - Run main go file (test functionality of 'normal' go program)
      continue-on-error: true
      run: ./compilerIFJ2020 < tests/main.go

  tests:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Tests (according to Makefile)
      run: make test
    
  kamil-test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build compiler (according to Makefile)
      run: make
    - name: Prepare enviroment (0)
      run: sudo cp -a tests/ifj-testsuite/. .
    - name: Prepare enviroment (1)
      run: rm -rf tests/inputFile.go tests/ifj-testsuite
    - name: Run Kamil's tests
      run: sudo python2 testsuite.py --compiler compilerIFJ2020
